"""initial schema

Revision ID: 8aa4e80cd3ce
Revises: 
Create Date: 2026-09-15 15:05:28.546587

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8aa4e80cd3ce"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inspectors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("badge_id", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inspectors_email"), "inspectors", ["email"], unique=True)
    op.create_table(
        "rules",
        sa.Column("rule_code", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("field_name", sa.String(length=60), nullable=False),
        sa.Column("condition_type", sa.String(length=20), nullable=False),
        sa.Column("expected_value", sa.String(length=255), nullable=True),
        sa.Column("expected_unit", sa.String(length=50), nullable=True),
        sa.Column("applicable_category", sa.String(length=100), nullable=False),
        sa.Column("legal_source", sa.String(length=500), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rules_active"), "rules", ["active"], unique=False)
    op.create_index(op.f("ix_rules_field_name"), "rules", ["field_name"], unique=False)
    op.create_index(op.f("ix_rules_rule_code"), "rules", ["rule_code"], unique=True)
    op.create_table(
        "inspections",
        sa.Column("inspector_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("overall_status", sa.String(length=40), nullable=False),
        sa.Column("inspection_location", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("finalized_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inspector_id"],
            ["inspectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inspections_inspector_id"), "inspections", ["inspector_id"], unique=False)
    op.create_index(op.f("ix_inspections_overall_status"), "inspections", ["overall_status"], unique=False)
    op.create_index(op.f("ix_inspections_stage"), "inspections", ["stage"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("inspection_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["inspectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_inspection_id"), "audit_logs", ["inspection_id"], unique=False)
    op.create_table(
        "inspector_reviews",
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("previous_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["inspectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inspector_reviews_inspection_id"),
        "inspector_reviews",
        ["inspection_id"],
        unique=False,
    )
    op.create_table(
        "product_images",
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("view_type", sa.String(length=20), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("image_quality", sa.String(length=20), nullable=True),
        sa.Column("quality_note", sa.String(length=255), nullable=True),
        sa.Column("processing_status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_images_inspection_id"), "product_images", ["inspection_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=True),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("batch_number", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_inspection_id"), "products", ["inspection_id"], unique=True)
    op.create_table(
        "extracted_fields",
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=60), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("normalized_value", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confidence_level", sa.String(length=10), nullable=False),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("validation_reason", sa.String(length=255), nullable=True),
        sa.Column("source_image_id", sa.UUID(), nullable=True),
        sa.Column("source_text", sa.Text(), nullable=True),
        sa.Column("manually_verified", sa.Boolean(), nullable=False),
        sa.Column("manually_edited", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_image_id"],
            ["product_images.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_extracted_fields_field_name"), "extracted_fields", ["field_name"], unique=False)
    op.create_index(
        op.f("ix_extracted_fields_inspection_id"),
        "extracted_fields",
        ["inspection_id"],
        unique=False,
    )
    op.create_table(
        "ocr_results",
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("ocr_confidence", sa.Float(), nullable=False),
        sa.Column("processing_status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["product_images.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ocr_results_image_id"), "ocr_results", ["image_id"], unique=True)
    op.create_table(
        "rule_results",
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=60), nullable=False),
        sa.Column("detected_value", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence_image_id", sa.UUID(), nullable=True),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("inspector_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_image_id"],
            ["product_images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["inspectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rule_results_inspection_id"), "rule_results", ["inspection_id"], unique=False)
    op.create_index(op.f("ix_rule_results_rule_id"), "rule_results", ["rule_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rule_results_rule_id"), table_name="rule_results")
    op.drop_index(op.f("ix_rule_results_inspection_id"), table_name="rule_results")
    op.drop_table("rule_results")
    op.drop_index(op.f("ix_ocr_results_image_id"), table_name="ocr_results")
    op.drop_table("ocr_results")
    op.drop_index(op.f("ix_extracted_fields_inspection_id"), table_name="extracted_fields")
    op.drop_index(op.f("ix_extracted_fields_field_name"), table_name="extracted_fields")
    op.drop_table("extracted_fields")
    op.drop_index(op.f("ix_products_inspection_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_product_images_inspection_id"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_index(op.f("ix_inspector_reviews_inspection_id"), table_name="inspector_reviews")
    op.drop_table("inspector_reviews")
    op.drop_index(op.f("ix_audit_logs_inspection_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_inspections_stage"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_overall_status"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_inspector_id"), table_name="inspections")
    op.drop_table("inspections")
    op.drop_index(op.f("ix_rules_rule_code"), table_name="rules")
    op.drop_index(op.f("ix_rules_field_name"), table_name="rules")
    op.drop_index(op.f("ix_rules_active"), table_name="rules")
    op.drop_table("rules")
    op.drop_index(op.f("ix_inspectors_email"), table_name="inspectors")
    op.drop_table("inspectors")
    # ### end Alembic commands ###
