"""conflict candidates and image quality default

Revision ID: ccc51659abe8
Revises: 8aa4e80cd3ce
Create Date: 2026-09-15 15:44:00.243138

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ccc51659abe8"
down_revision: str | None = "8aa4e80cd3ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("extracted_fields", sa.Column("candidates", sa.JSON(), nullable=True))
    # Backfill existing rows before enforcing NOT NULL — images uploaded
    # before this migration have no quality signal yet.
    op.execute("UPDATE product_images SET image_quality = 'UNKNOWN' WHERE image_quality IS NULL")
    op.alter_column("product_images", "image_quality", existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product_images", "image_quality", existing_type=sa.VARCHAR(length=20), nullable=True)
    op.drop_column("extracted_fields", "candidates")
    # ### end Alembic commands ###
